; screen size
DEF SCREEN_WIDTH  EQU 20 ; tiles
DEF SCREEN_HEIGHT EQU 18 ; tiles

; background map size
DEF BG_MAP_WIDTH  EQU 32 ; tiles
DEF BG_MAP_HEIGHT EQU 32 ; tiles

; cgb palette size
DEF CGB_PAL_SIZE EQU 8 ; bytes
DEF palettes EQUS "* CGB_PAL_SIZE"

DEF NUM_BACKGROUND_PALETTES EQU 8
DEF NUM_OBJECT_PALETTES     EQU 8

DEF PALRGB_WHITE EQU (31 << 10 | 31 << 5 | 31)

; tile size
DEF TILE_SIZE EQU 16 ; bytes
DEF tiles EQUS "* TILE_SIZE"

DEF TILE_SIZE_1BPP EQU 8 ; bytes
DEF tiles_1bpp EQUS "* TILE_SIZE_1BPP"

; icon tile offsets
DEF ICON_TILE_BASIC_POKEMON   EQU $b0
DEF ICON_TILE_STAGE_1_POKEMON EQU $b4
DEF ICON_TILE_STAGE_2_POKEMON EQU $b8
DEF ICON_TILE_TRAINER         EQU $bc

DEF ICON_TILE_FIRE            EQU $c0
DEF ICON_TILE_GRASS           EQU $c4
DEF ICON_TILE_LIGHTNING       EQU $c8
DEF ICON_TILE_WATER           EQU $cc
DEF ICON_TILE_FIGHTING        EQU $d0
DEF ICON_TILE_PSYCHIC         EQU $d4
DEF ICON_TILE_DARKNESS        EQU $d8
DEF ICON_TILE_COLORLESS       EQU $dc
DEF ICON_TILE_ENERGY          EQU $e0
